[package]
name = "cvg"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
molmap = { version = "0.1.0", path = "../../molmap/molmap" }
molmap-cvg = { version = "0.1.0", path = "../molmap-cvg" }
